// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stargazer.Orleans.Users.EntityFrameworkCore.PostgreSQL.DbMigrations;

#nullable disable

namespace Stargazer.Orleans.Users.EntityFrameworkCore.PostgreSQL.DbMigrations.Migrations
{
    [DbContext(typeof(EfDbMigrationsContext))]
    [Migration("20260326033816_AllowNullEmailAndPhone")]
    partial class AllowNullEmailAndPhone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stargazer.Orleans.Users.Domain.Permissions.PermissionData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifier_id");

                    b.Property<DateTime>("LastModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_sys_permissions_category");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_sys_permissions_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_sys_permissions_is_active");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_sys_permissions_type");

                    b.ToTable("sys_permissions", (string)null);
                });

            modelBuilder.Entity("Stargazer.Orleans.Users.Domain.Roles.RoleData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<Guid>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifier_id");

                    b.Property<DateTime>("LastModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_sys_roles_is_active");

                    b.HasIndex("IsDefault")
                        .HasDatabaseName("idx_sys_roles_is_default");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_sys_roles_name");

                    b.HasIndex("Priority")
                        .HasDatabaseName("idx_sys_roles_priority");

                    b.ToTable("sys_roles", (string)null);
                });

            modelBuilder.Entity("Stargazer.Orleans.Users.Domain.Roles.RolePermissionData", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LastModifierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifyTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("idx_sys_role_permissions_permission_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_sys_role_permissions_role_id");

                    b.ToTable("sys_role_permissions", (string)null);
                });

            modelBuilder.Entity("Stargazer.Orleans.Users.Domain.UserRoles.UserRoleData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("ExpireTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifier_id");

                    b.Property<DateTime>("LastModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpireTime")
                        .HasDatabaseName("idx_sys_user_roles_expire_time")
                        .HasFilter("expire_time IS NOT NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_sys_user_roles_is_active");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_sys_user_roles_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_sys_user_roles_user_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("idx_sys_user_roles_user_role");

                    b.ToTable("sys_user_roles", (string)null);
                });

            modelBuilder.Entity("Stargazer.Orleans.Users.Domain.Users.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modifier_id");

                    b.Property<DateTime>("LastModifyTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modify_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("secret_key");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique()
                        .HasDatabaseName("idx_sys_users_account");

                    b.HasIndex("CreationTime")
                        .HasDatabaseName("idx_sys_users_creation_time");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_sys_users_email")
                        .HasFilter("(email IS NOT NULL)");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_sys_users_is_active");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_sys_users_phone_number")
                        .HasFilter("(phone_number IS NOT NULL)");

                    b.ToTable("sys_users", (string)null);
                });

            modelBuilder.Entity("Stargazer.Orleans.Users.Domain.Roles.RolePermissionData", b =>
                {
                    b.HasOne("Stargazer.Orleans.Users.Domain.Permissions.PermissionData", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stargazer.Orleans.Users.Domain.Roles.RoleData", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Stargazer.Orleans.Users.Domain.UserRoles.UserRoleData", b =>
                {
                    b.HasOne("Stargazer.Orleans.Users.Domain.Roles.RoleData", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stargazer.Orleans.Users.Domain.Users.UserData", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stargazer.Orleans.Users.Domain.Permissions.PermissionData", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Stargazer.Orleans.Users.Domain.Roles.RoleData", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Stargazer.Orleans.Users.Domain.Users.UserData", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
